name: Run Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chrome]
        
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run tests
      run: mvn test
