# This is a basic workflow that is manually triggered

name: Greeting the user on each pull and push call

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

      # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runner's shell
    - name: Send greeting
      run: echo "I am a job running every time you push or pull on the main branch "

